# Generated by Django 4.2 on 2023-05-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado_factura',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.usuario'),
        ),
        migrations.DeleteModel(
            name='Info_Usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
