# Generated by Django 4.2 on 2023-06-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('tienda', '0002_alter_encabezado_factura_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezado_factura',
            name='direccion_despacho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.info_usuario'),
            preserve_default=False,
        ),
    ]
