# Generated by Django 4.2 on 2023-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_encabezado_factura_direccion_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado_factura',
            name='total',
            field=models.FloatField(),
        ),
    ]
