# Generated by Django 4.2 on 2023-06-11 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_encabezado_factura_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encabezado_factura',
            name='base_imp',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_max',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_min',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=False)),
                ('id_encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.encabezado_factura')),
            ],
        ),
    ]
