# Generated by Django 4.2 on 2023-06-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('tienda', '0007_remove_encabezado_factura_base_imp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.usuario'),
            preserve_default=False,
        ),
    ]
