# Generated by Django 4.2 on 2023-06-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pedido_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_cliente',
        ),
    ]
