# Generated by Django 4.2 on 2023-06-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_pedido_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprod',
            name='imagen_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='tienda/'),
        ),
    ]
