# Generated by Django 4.2 on 2023-06-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_categoriaprod_imagen_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezado_factura',
            name='dolar',
            field=models.FloatField(default=20),
        ),
    ]
