# Generated by Django 4.2 on 2023-06-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_encabezado_factura_despachado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encabezado_factura',
            name='despachado',
        ),
    ]
