# Generated by Django 4.2 on 2023-05-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemscarro',
            old_name='carro',
            new_name='Idcarro',
        ),
    ]
