# Generated by Django 4.2 on 2023-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_rename_carro_itemscarro_idcarro'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscarro',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
